In [4]:
input = [3,4,5,6,7,6,7,5,6,7,8,9]
output = [3,4,5,56,6,7,8,9,0,0,7,4]

In [5]:
w = 0.0
b = 0.0
lr = .01

In [6]:
# Python code to implement neural network
for epoch in range(1000):
    total_loss = 0
    for x,y in zip(input,output):
        Y_pred = w*x+b
        error = Y_pred-y
        loss = error**2
        total_loss = total_loss + loss
        
        dw = 2*error*x  # rate of loss change w.r.t w => dl/dw as per derived formula
        db = 2*error    # rate of loss change w.r.t b => dl/db as per derived formula
        
        w = w - lr*dw
        b = b - lr*db
        
    if epoch % 10 == 0:
        print(f"epoch {epoch} | Loss : {total_loss}  | w : {w} , b: {b}")

test_data = 7 
prediction = w*test_data + b 
print(prediction)   

epoch 0 | Loss : 4765.74205765353  | w : -0.02274495796089715 , b: 0.234673196595955
epoch 10 | Loss : 4741.506151986847  | w : -0.2521193533024988 , b: 2.4057629903058793
epoch 20 | Loss : 4727.5764121731045  | w : -0.45165831217269514 , b: 4.294452424910856
epoch 30 | Loss : 4720.637761491353  | w : -0.625242621998145 , b: 5.937474187862894
epoch 40 | Loss : 4718.521124029562  | w : -0.7762482841915561 , b: 7.3667830324367145
epoch 50 | Loss : 4719.645961229264  | w : -0.9076121732285329 , b: 8.610177258394142
epoch 60 | Loss : 4722.86919446392  | w : -1.021889155245383 , b: 9.691839354737802
epoch 70 | Loss : 4727.371905119765  | w : -1.1213017770443898 , b: 10.632806319391081
epoch 80 | Loss : 4732.5744895107555  | w : -1.2077834918966002 , b: 11.45137880294375
epoch 90 | Loss : 4738.073230935231  | w : -1.2830162628308601 , b: 12.163477033806155
epoch 100 | Loss : 4743.592978119958  | w : -1.3484632747468397 , b: 12.78295044707873
epoch 110 | Loss : 4748.951924222351  | w : -1.405

In [11]:
input = [1,2,3,4,5]
output = [2,4,6,8,10]

In [12]:
w1, b1 = .1, 0.0
w2, b2 = -0.1, 0.0
w3, w4 = .1, .1
b3 = 0.0
lr = .01

In [13]:
def relu(x):
    return max(0,x)

In [14]:
def relu_derivative(x):
    return 1 if x>0 else 0 

In [15]:
for epoch in range(100):
    total_loss = 0 
    for x,y in zip(input,output):
        z1 = w1*x + b1
        h1 = relu(z1)
        
        z2 = w2*x + b2
        h2 = relu(z2)
        
        Y_pred = w3*h1 + w4*h2 + b3
        
        error = Y_pred - y 
        loss  = error**2
        total_loss = total_loss + loss
        
        dl_dy = 2*error
        
        # Backward propagation
        dw3 = dl_dy * h1
        dw4 = dl_dy * h2
        db3 = dl_dy
        
        dh1 = dl_dy * w3
        dh2 = dl_dy * w4
        
        dz1 = dh1* relu_derivative(z1)
        dz2 = dh2* relu_derivative(z2)
        
        dw1 = dz1 * x
        db1 = dz1
        
        dw2 = dz2 * x
        db2 = dz2
        
        w1 = w1 - lr*dw1
        w2 = w2 - lr*dw2
        w3 = w3 - lr*dw3
        w4 = w4 - lr*dw4
        
        
        b1 = b1 - lr*db1
        b2 = b2 - lr*db2
        b3 = b3 - lr*db3
        
    if epoch % 10 == 0:
        print(f"epoch {epoch} | Loss : {total_loss} ")
        
        
def prediction(x):
    z1 = w1*x + b1
    h1 = relu(z1)
        
    z2 = w2*x + b2
    h2 = relu(z2)
        
    y_output = w3*h1 + w4*h2 + b3
    return y_output     
                
prediction(9)

epoch 0 | Loss : 197.58784675778605 
epoch 10 | Loss : 0.7822743866736906 
epoch 20 | Loss : 0.2777331306080438 
epoch 30 | Loss : 0.09441733364350127 
epoch 40 | Loss : 0.03110053083599192 
epoch 50 | Loss : 0.010038059173204952 
epoch 60 | Loss : 0.00320027527189278 
epoch 70 | Loss : 0.0010129806992875082 
epoch 80 | Loss : 0.0003193181207800499 
epoch 90 | Loss : 0.00010042211687133479 


17.99692772369434

In [17]:
import tensorflow as tf
import numpy as np

In [18]:
input

[1, 2, 3, 4, 5]

In [19]:
output

[2, 4, 6, 8, 10]

In [20]:
x = np.array(input,dtype=float)
y = np.array(output, dtype=float)

In [43]:
model = tf.keras.Sequential([tf.keras.layers.Dense(20,activation='relu',input_shape = [1]),
                    tf.keras.layers.Dense(1)])

In [44]:
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=.001),loss='mean_squared_error')

In [ ]:
model.fit(x,y,epochs=1000,verbose=1)
model.save("euron_gen_ai_first.h5")     # old format
model.save("euron_gen_ai_first.keras")  # new format in keras

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1.1954e-06
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.1925e-06
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.1901e-06
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1873e-06
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1843e-06
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1821e-06
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1790e-06
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1765e-06
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.1739e-06
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1711e-06
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1685e-06
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1658e-06
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.1633e-06
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1607e-06
Epoch 15/1000
1

In [59]:
model.predict(np.array([90]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[179.98064]], dtype=float32)

In [92]:
data = 'help'
char2idx = {'h':0 , 'e':1 , "l":2 , "p":3}
idx2char = {v : k for k , v in char2idx.items()}

In [93]:
char2idx

{'h': 0, 'e': 1, 'l': 2, 'p': 3}

In [94]:
idx2char

{0: 'h', 1: 'e', 2: 'l', 3: 'p'}

In [95]:
input_seq = [char2idx[c] for c in data[:-1]]
target_seq = [char2idx[c] for c in data [1:]]

In [96]:
input_seq

[0, 1, 2]

In [97]:
target_seq

[1, 2, 3]

In [98]:
x = tf.one_hot(input_seq, depth=4)
x = tf.expand_dims(x, axis=0)
y = tf.expand_dims(target_seq, axis=0)

In [99]:
x

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)>

In [100]:
y

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [101]:
model = tf.keras.Sequential([tf.keras.layers.LSTM(8,return_sequences=True , input_shape=(3,4)), 
                            tf.keras.layers.Dense(4,activation='linear')])

In [102]:
model.compile(optimizer='adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))

In [103]:
for epoch in range(201):
    model.train_on_batch(x,y)
    
    if epoch % 50  == 0:
        output = model(x)
        print(output)
        pred = tf.argmax(output,axis = -1).numpy()[0]
        pred_char = "".join([idx2char[i] for i in pred])
        print(f"epoch : {epoch} , prediction : {pred_char} , loss : {loss} ")

tf.Tensor(
[[[ 0.02183915  0.0414026   0.03855495 -0.09139422]
  [ 0.09831835  0.03133561  0.03470218 -0.00223053]
  [ 0.02233939 -0.17199785 -0.23546845  0.11009325]]], shape=(1, 3, 4), dtype=float32)
epoch : 0 , prediction : ehp , loss : 5.823832244906861e-07 
tf.Tensor(
[[[-0.0880536   0.11779699  0.13282171 -0.03125007]
  [-0.06981952  0.07538491  0.1850458   0.09941934]
  [-0.21083558 -0.23498881 -0.21503688  0.332813  ]]], shape=(1, 3, 4), dtype=float32)
epoch : 50 , prediction : llp , loss : 5.823832244906861e-07 
tf.Tensor(
[[[-0.1834508   0.21765442  0.26857844 -0.01484397]
  [-0.23731539  0.13270532  0.40667668  0.17194949]
  [-0.46790168 -0.36437783 -0.22188845  0.6070787 ]]], shape=(1, 3, 4), dtype=float32)
epoch : 100 , prediction : llp , loss : 5.823832244906861e-07 
tf.Tensor(
[[[-0.27871484  0.36202013  0.45218354 -0.07001055]
  [-0.4247564   0.2257666   0.7537736   0.1721521 ]
  [-0.7690349  -0.58860487 -0.2635091   0.94312155]]], shape=(1, 3, 4), dtype=float32)
epoch 

In [105]:
model.save('euron_lstm.keras')