In [2]:
# Using requests library for embeddings
import os
import requests
import numpy as np
from dotenv import load_dotenv

load_dotenv()

EURI_API_KEY = os.getenv("EURI_API_KEY")

def generate_embeddings():
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {EURI_API_KEY}"
    }
    payload = {
        "input": "The food was delicious and the service was excellent.",
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    print(f"Generated embedding with shape: {embedding.shape}")
    print(f"First 5 values: {embedding[:5]}")
    
    # Example: Calculate vector norm
    norm = np.linalg.norm(embedding)
    print(f"Vector norm: {norm}")
    
    return embedding

In [3]:
generate_embeddings()

Generated embedding with shape: (1536,)
First 5 values: [-0.03244253 -0.00839565 -0.06356495 -0.04268333  0.04704366]
Vector norm: 1.0000000296607552


array([-0.03244253, -0.00839565, -0.06356495, ..., -0.00225143,
        0.05896459, -0.03152246])

In [3]:
# Using requests library for embeddings
import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {EURI_API_KEY}"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    print(f"Generated embedding with shape: {embedding.shape}")
    print(f"First 5 values: {embedding[:5]}")
    
    # Example: Calculate vector norm
    norm = np.linalg.norm(embedding)
    print(f"Vector norm: {norm}")
    
    return embedding

In [7]:
data1 = generate_embeddings("my name is sudhanshu kumar")

Generated embedding with shape: (1536,)
First 5 values: [-0.00965959 -0.02545136 -0.0277467  -0.01005902 -0.06116427]
Vector norm: 1.0000000358807721


In [8]:
data1

array([-0.00965959, -0.02545136, -0.0277467 , ...,  0.00493669,
        0.01804773, -0.00078129])

In [9]:
data2 = generate_embeddings("sudhanshu kumar take class for tech")

Generated embedding with shape: (1536,)
First 5 values: [-0.04761972  0.00898147  0.00278912 -0.05086942  0.02151971]
Vector norm: 0.999999969675327


In [10]:
data2

array([-0.04761972,  0.00898147,  0.00278912, ...,  0.02084162,
        0.02370751,  0.000431  ])

In [11]:
import numpy as np

In [12]:
data1, data2

(array([-0.00965959, -0.02545136, -0.0277467 , ...,  0.00493669,
         0.01804773, -0.00078129]),
 array([-0.04761972,  0.00898147,  0.00278912, ...,  0.02084162,
         0.02370751,  0.000431  ]))

In [ ]:
cosign_similarity = np.dot(data1, data2)/(np.linalg.norm(data1)*np.linalg.norm(data2))
# cosign_similarity -> always looks for how close the angle is between two vectors
# Apart from cosign, there euclidean distance, manhattan distance, jaccard distance as well.
# For e.g. FASSI (facebook AI Similarity Search Index - vector DB from Facebook) is used for similarity search and uses Approximate Nearest Neighbour algorithm.

In [21]:
cosign_distance = 1 - cosign_similarity

In [22]:
cosign_distance

np.float64(0.44568355460644316)

In [23]:
data3 = generate_embeddings("people call me by my name sudhanshu kumar")

Generated embedding with shape: (1536,)
First 5 values: [ 0.02695428 -0.05315723 -0.00928021  0.01220926 -0.05419032]
Vector norm: 1.0000000276464485


In [24]:
data1, data2, data3

(array([-0.00965959, -0.02545136, -0.0277467 , ...,  0.00493669,
         0.01804773, -0.00078129]),
 array([-0.04761972,  0.00898147,  0.00278912, ...,  0.02084162,
         0.02370751,  0.000431  ]),
 array([ 0.02695428, -0.05315723, -0.00928021, ...,  0.0039504 ,
         0.01880695,  0.00535622]))

In [25]:
cosign_similarty2 = np.dot(data1,data3)/(np.linalg.norm(data1)*np.linalg.norm(data3))

In [26]:
cosign_similarty2

np.float64(0.8295106197047585)

In [27]:
cosign_distance2 = 1 - cosign_similarty2

In [28]:
cosign_distance2

np.float64(0.17048938029524152)

In [ ]:
dist - data 1 and data2 - 0.0.44568355460644316
dist data1 data 3 - .0.17048938029524152